# Generated by Django 3.1.4 on 2021-07-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesAgent',
            new_name='SalesPerson',
        ),
    ]
